### ISSUE TITLE
2022-06-30 Open session on procrastination

### ISSUE THREAD

**Issue by JaroCamphuijsen** [NLeSC/Soft-Skills-SIG#10]

**Comment by bvreede** [comment]
Team Beta had a discussion today about **context switching** as a skill, and we thought it might be a good subject also to address with the Soft Skills Sig. I'm tagging it onto this issue, as it is not unrelated :) (but of course happy to generate a new issue if necessary!)

**Comment by JaroCamphuijsen** [comment]
@bvreede I think it would be nice to create a new issue, I agree it has overlap with procrastination but it is definitely worth its own issue. I think it's better to think of it as separate topics and merge them later into a single session if that seems suitable.
