### ISSUE TITLE
2022-03-17 Open discussion on burnouts

### ISSUE THREAD

**Issue by JaroCamphuijsen** [NLeSC/Soft-Skills-SIG#11]
Topics for discussion:
- How to recognize early symptoms?
- How do symptoms evolve over time / different stages?
- What are responsibilities of the employer? How does it fit with the vitality program?
- How can fellow employees help? Burnout buddy system?
- What are solutions that worked for you?
- What to do about the "we all say we think it's not cool to work overtime and stress for a deadline all the time and take another one for the team, but we're just saying that so that the rest will work less hard so we can overtake them" mindset.

**Comment by goord** [comment]
Huh that last item seems really odd to me, is that mindset actually adopted by any of us?

**Comment by cwmeijer** [comment]
The last item is indeed an odd one. Is this mindset really adopted or was this item spawned from someone's _fear_? That would be a fear that colleagues are not sincere when promoting a relaxed/sustainable working pace and mindset. Worth discussing none-the-less.

**Comment by JaroCamphuijsen** [comment]
@goord @cwmeijer It can be indeed considered to be a strange twist of the mind, but definitely a mindset that can have negative consequences. It was mentioned in a discussion on teams as a reaction to the statement that we do not have a very competitive culture at the eScience Center and I added it because there was some recognition of the mindset by other discussion participants.  
Maybe it should actually be the broader topic of "Influence of work culture and mindset at the eScience Center on mental health", with this one mindset just as an example.
